import { ethers } from 'ethers';
import { ERC20_ABI, VAULT_ABI } from './contracts';
import { USDC_ADDRESS, VAULT_ADDRESS, USDC_DECIMALS } from '../utils/constants';




//generated by antigravity

export type TxStatus =
    | 'IDLE'
    | 'CHECKING'
    | 'APPROVING'
    | 'DEPOSITING'
    | 'WITHDRAWING'
    | 'SUCCESS'
    | 'REJECTED'
    | 'FAILED';

export const approveAndDeposit = async ({
    provider,
    signer,
    userAddress,
    amount,
    onStatus,
}: {
    provider: any;
    signer: any;
    userAddress: string;
    amount: string;
    onStatus: (s: TxStatus) => void;
}) => {
    try {
        onStatus('CHECKING');

        const usdc = new ethers.Contract(USDC_ADDRESS, ERC20_ABI, provider);
        const vault = new ethers.Contract(VAULT_ADDRESS, VAULT_ABI, signer);

        const parsedAmount = ethers.parseUnits(amount, USDC_DECIMALS);

        // 1️⃣ Check allowance
        const allowance = await usdc.allowance(userAddress, VAULT_ADDRESS);

        if (allowance < parsedAmount) {
            // 2️⃣ Approve
            onStatus('APPROVING');

            const usdcWithSigner = usdc.connect(signer);
            // @ts-ignore
            const approveTx = await usdcWithSigner.approve(
                VAULT_ADDRESS,
                parsedAmount
            );

            await approveTx.wait();
        }

        // 3️⃣ Deposit
        onStatus('DEPOSITING');

        const depositTx = await vault.deposit(parsedAmount);
        await depositTx.wait();

        onStatus('SUCCESS');
    } catch (err: any) {
        if (err?.code === 4001 || err?.info?.error?.code === 4001) {
            onStatus('REJECTED');
        } else {
            console.error(err);
            onStatus('FAILED');
        }
        throw err;
    }
};

export const withdrawFunds = async ({
    signer,
    amount, // shares amount usually, but we'll assume 1:1 for simplicity or UI handles conversion
    onStatus,
}: {
    signer: any;
    amount: string;
    onStatus: (s: TxStatus) => void;
}) => {
    try {
        onStatus('WITHDRAWING');
        const vault = new ethers.Contract(VAULT_ADDRESS, VAULT_ABI, signer);

        // Assuming amount is shares. In real app, might need to convert USD -> Shares
        const parsedAmount = ethers.parseUnits(amount, USDC_DECIMALS);

        const tx = await vault.withdraw(parsedAmount);
        await tx.wait();

        onStatus('SUCCESS');
    } catch (err: any) {
        if (err?.code === 4001 || err?.info?.error?.code === 4001) {
            onStatus('REJECTED');
        } else {
            console.error(err);
            onStatus('FAILED');
        }
        throw err;
    }
};
